# Generated by Django 3.2.9 on 2021-11-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=30)),
                ('raca', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=300)),
                ('local', models.CharField(max_length=150)),
                ('info', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
