# Generated by Django 3.2.9 on 2021-11-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cadastro_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=14)),
                ('descricao', models.CharField(max_length=300)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
