# Generated by Django 3.2.9 on 2021-11-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211102_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
