# Generated by Django 3.2.9 on 2021-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contato_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
