# Generated by Django 3.2.9 on 2021-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211104_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='image',
            field=models.ImageField(default='images/profile/avatar-default-icon.png', upload_to='media/images/'),
        ),
    ]
